site_name: Grafana Documentation
#site_url: http://docs.grafana.com/
site_url: /
site_description: Documentation for Grafana, The Graphite and Influxdb dashboard and graph composer
site_favicon: img/fav32.png

dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/grafana/grafana/

docs_dir: sources

include_search: true

use_absolute_urls: true

# theme: docker
theme_dir: ./theme/mkdocs/
theme_center_lead: false

copyright: Copyright &copy; 2014-2015, Docker, Inc.
google_analytics: ['UA-6096819-11', 'docker.io']


pages:

# Introduction:
- ['index.md', 'About', 'Docker']
- ['test.md', 'Tutorials', 'Test']

- ['jsearch.md', '**HIDDEN**']
